#ifndef SDL_LATEX_TEX_CONFIG_H
#define SDL_LATEX_TEX_CONFIG_H

#ifndef TEX_MAX_LATEX_FILE_SIZE
	#define TEX_MAX_LATEX_FILE_SIZE 1024
#endif

#ifndef TEX_DEFAULT_GENERATION_FOLDER
	#define TEX_DEFAULT_GENERATION_FOLDER "latex"
#endif

#ifndef TEX_MAX_LATEX_FILE_PATH_SIZE
	#define TEX_MAX_LATEX_FILE_PATH_SIZE 512
#endif

#ifndef TEX_MAX_PDFLATEX_COMMAND_SIZE
	#define TEX_MAX_PDFLATEX_COMMAND_SIZE 600
#endif

#ifndef TEX_MAX_CONVERT_COMMAND_SIZE
	#define TEX_MAX_CONVERT_COMMAND_SIZE 1500
#endif


#endif